### ISSUE TITLE
hostpath can't be set through helm

### ISSUE THREAD

**Issue by noopple** [Addyvan/valheim-k8s#13]
I tried to install valheim server on k8s, but set storage.hostvol.path as /var/data/valheim.

Container stucked on status ContainerCreating because of wrong hostpath. It was set /data/valheim

**Comment by Addyvan** [comment]
@noopple The path has to exist on the underlying node for the `hostPath` to work. 

What's your setup like? I personally just `ssh`'ed onto the node and ran `sudo mkdir /data/valheim`. 

A possible soln to avoid this would be to add an init container or job which creates the directory if it is missing.

**Comment by Addyvan** [comment]
@noopple Interesting. It could be an issue with the autodeploy if you see this issue when pulling the chart? 

Running the following `helm template chart --set storage.hostvol.path=/test` inside the main branch returns the correct result for me:
```yaml
volumes:
  - name: gamefiles
    hostPath:
      path: /test
      type: Directory
```

I'll test it out when pulling the helm chart.

**Comment by Addyvan** [comment]
Ok! @noopple  That was it. The CI/CD is setup to update the chart index when the version file is edited...

It should be good now. Thanks for spotting that.

**Comment by Addyvan** [comment]
I'm going to close this since it's fixed.
