### ISSUE TITLE
Add nodeSelector support

### ISSUE THREAD

**Issue by gtaylor** [Addyvan/valheim-k8s#14]
This'll make sure that multi-node homelabs won't lose state between pod recreations.

**Comment by Addyvan** [comment]
Hi @gtaylor!

Good point, I've currently got a nodeSelector in use on my running instance actually. 

I've gone ahead and PR'ed up the addition [here](https://github.com/Addyvan/valheim-k8s/pull/15)

**Comment by gtaylor** [comment]
Thanks, @Addyvan! That's perfect.
