### ISSUE TITLE
tcp/http health probe endpoint

### ISSUE THREAD

**Issue by motmot80** [Addyvan/valheim-k8s#23]
This is more or less a painful unresolved Microsoft issue, but it is not possible to use the a Microsoft Azure load balancer udp rule without a tcp/http health probe. The Valheim pod is UDP-only and has no tcp/http health endpoints so it is necessary to create an addon DaemonSet to cover this need. But this really does not show the health status of the Valheim instance...

Having all the great support services already on board it would be great having a health endpoint, too.

**Comment by Addyvan** [comment]
@motmot80, I believe the valheim-docker repo added a status endpoint which uses http. 

We could add a param to enable that and add a health probe. I believe the param is `STATUS_HTTP`.

See the [README.md for that here](https://github.com/lloesche/valheim-server-docker) .

**Comment by Addyvan** [comment]
If anyone is hoping for this to be added to the project, thumbs up this comment and I'll see to it.

**Comment by Addyvan** [comment]
@bdelwood Mentioned wanting to pick this up, reopening.
