### ISSUE TITLE
Warn user of HostVol volatility on a Managed GCloud

### ISSUE THREAD

**Issue by GreeFine** [Addyvan/valheim-k8s#25]
Today my node got updated automaticaly by GCloud.
Unfortunalty the node containing the HostVol and thus our game world was deleted.

I think it would be nice to warn of this issue on the Readme.

I was kindof aware of this issue with hostvol but didn't realy pay enough attention to it.
Also i wasn't expecting my node to be updated, but it's to late.

**Comment by Addyvan** [comment]
Sorry to hear... That must suck! I'm running an on prem cluster and as such have control / access over the underlying hostVols. 

The option to use a PVC was added in a few weeks ago. If you are using GKE these docs are likely relevant to getting you running with a more secure data store: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

**Comment by Addyvan** [comment]
@GreeFine I've gone ahead and updated the README to include a warning about this. Thanks for bringing this up!

[PR here](https://github.com/Addyvan/valheim-k8s/pull/26)
