### ISSUE TITLE
Google Autopilot Ephemeral Storage Limit Exceeded

### ISSUE THREAD

**Issue by bakester14** [Addyvan/valheim-k8s#39]
For whatever reason, GCP Autopilot K8s clusters set an ephemeral storage limit of 1Gi: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#default_container_resource_requests

This seems to be exceeded, at least during initial setup. I get errors in the logs that just say `'/home/valheim/Steam/logs/stderr.txt'`, and a notice in the console that the limit has been exceeded. Does anyone know what a good value for ephemeral storage limit should be? I'm happy to make the change, just don't really know what to put in that space.

If no one responds to this in a few days I'll submit a PR with a 10Gi Ephemeral storage request.

Sick stuff btw! Thank you!

**Comment by bakester14** [comment]
Just confirmed that setting the ephemeral storage value like `--set resources.limits.ephemeral-storage="10Gi"` lets the container start up fine. No idea if it will stay up, but that's ok.

Probably as simple a change as a note in the readme. Please let me know if that is preferable, or the first fix I offered was preferable, and I can make the change. Cheers!

**Comment by Addyvan** [comment]
I'm going to assume you are persisting the world to some sort of PVC. 

Perhaps the container is making use of ephemeral (container) storage to save some data at runtime. Based off that error, Ill go ahead and guess that `/home/valheim/Steam/logs/` should be mapped/mounted elsewhere.
