### ISSUE TITLE
Please use the Release name in the name of created k8s objects

### ISSUE THREAD

**Issue by TBBle** [Addyvan/valheim-k8s#42]
Using the Release name in the k8s object names ensures that multiple installations of the chart in a single namespace cannot conflict, and also helps identify resources that belong together.

The default `helm create` template provides an example for this as a named template [`<CHART>.fullname`](https://github.com/helm/helm/blob/v3.7.2/pkg/chartutil/create.go#L433-L449), which also supports overriding either the entire 'fullname' or just the `.Chart.Name` aspect, and can then be used as the [name](https://github.com/helm/helm/blob/v3.7.2/pkg/chartutil/create.go#L280-L281) or [name prefix](https://github.com/helm/helm/blob/v3.7.2/pkg/chartutil/create.go#L492-L493) for objects created by the chart.

Helpfully, all resources currently created have "valheim-server" as a name or prefix, so this is a reasonably easy thing to change.

However, for continuity when upgrading, either the default for `fullnameOverride` would be "valheim-server", and that's stuck there forever, or at some point users upgrading need to know to add that setting to their config when upgrading. Either one is a pain. >_<

**Comment by todaywasawesome** [comment]
Fixed in PR#50

**Comment by Addyvan** [comment]
> Fixed in #50

Yep, closing.
